//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.02 at 10:02:07 PM IST 
//


package com.bmc.cloud.bsasimulator.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VMDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VMDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="OS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NICCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="RAM" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VMDetail", propOrder = {
    "id",
    "os",
    "nicCount",
    "ram"
})
public class VMDetail {

    protected int id;
    @XmlElement(name = "OS", required = true)
    protected String os;
    @XmlElement(name = "NICCount")
    protected int nicCount;
    @XmlElement(name = "RAM")
    protected int ram;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the os property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOS() {
        return os;
    }

    /**
     * Sets the value of the os property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOS(String value) {
        this.os = value;
    }

    /**
     * Gets the value of the nicCount property.
     * 
     */
    public int getNICCount() {
        return nicCount;
    }

    /**
     * Sets the value of the nicCount property.
     * 
     */
    public void setNICCount(int value) {
        this.nicCount = value;
    }

    /**
     * Gets the value of the ram property.
     * 
     */
    public int getRAM() {
        return ram;
    }

    /**
     * Sets the value of the ram property.
     * 
     */
    public void setRAM(int value) {
        this.ram = value;
    }

}
